
#ifndef AIWARE_RUNTIME_SELFTESTDATA_EXPORT_H
#define AIWARE_RUNTIME_SELFTESTDATA_EXPORT_H

#ifdef AIWARE_RUNTIME_SELFTESTDATA_STATIC_DEFINE
#  define AIWARE_RUNTIME_SELFTESTDATA_EXPORT
#  define AIWARE_RUNTIME_SELFTESTDATA_NO_EXPORT
#else
#  ifndef AIWARE_RUNTIME_SELFTESTDATA_EXPORT
#    ifdef aiware_runtime_selftestdata_EXPORTS
        /* We are building this library */
#      define AIWARE_RUNTIME_SELFTESTDATA_EXPORT 
#    else
        /* We are using this library */
#      define AIWARE_RUNTIME_SELFTESTDATA_EXPORT 
#    endif
#  endif

#  ifndef AIWARE_RUNTIME_SELFTESTDATA_NO_EXPORT
#    define AIWARE_RUNTIME_SELFTESTDATA_NO_EXPORT 
#  endif
#endif

#ifndef AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED
#  define AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED_EXPORT
#  define AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED_EXPORT AIWARE_RUNTIME_SELFTESTDATA_EXPORT AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED
#endif

#ifndef AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED_NO_EXPORT
#  define AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED_NO_EXPORT AIWARE_RUNTIME_SELFTESTDATA_NO_EXPORT AIWARE_RUNTIME_SELFTESTDATA_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef AIWARE_RUNTIME_SELFTESTDATA_NO_DEPRECATED
#    define AIWARE_RUNTIME_SELFTESTDATA_NO_DEPRECATED
#  endif
#endif

#endif /* AIWARE_RUNTIME_SELFTESTDATA_EXPORT_H */
